# After initial start need to do 
#     docker exec -it gpodder_app_1 python manage.py migrate
version: '2.0'

volumes:
    db:

services:
    app:
        build: .
        restart: always
        depends_on:
            - db
            - redis
        environment:
            EMAIL_BACKEND: django.core.mail.backends.console.EmailBackend
            SECRET_KEY: ${SECRET_KEY}
            DATABASE_URL: postgres://mygpo:mygpo@db/mygpo
            CELERY_BROKER_URL: "redis://redis:6379//"
            # Debug must be true when using development server
            DEBUG: ${DEBUG}
        volumes:
            - "./static:/usr/src/mygpo/staticfiles"
            - "./media:/usr/src/mygpo/media"
        ports:
            - "8000:8000"
        networks:
            - default
            - caddy

    db:
        image: "postgres:13.2-alpine"
        restart: always
        volumes:
            - "db:/var/lib/postgresql/data"
            - "./postgres_init:/docker-entrypoint-initdb.d"
        environment:
            POSTGRES_USER: mygpo
            POSTGRES_PASSWORD: mygpo
        restart: always
        expose: 
            - "5432"

    redis:
        image: "redis:6.2-alpine"
        restart: always

    beat:
        image: gpodder_app
        restart: always
        depends_on:
            - app
        environment:
            EMAIL_BACKEND: django.core.mail.backends.console.EmailBackend
            SECRET_KEY: ${SECRET_KEY}
            DATABASE_URL: postgres://mygpo:mygpo@db/mygpo
            LOGGING_CELERY_LEVEL: INFO
        entrypoint: 
                - celery 
                - -A 
                - mygpo 
                - beat 
                - -b 
                - redis://redis:6379// 
                - --pidfile 
                - /tmp/celerybeat.pid 
                - --scheduler 
                - django_celery_beat.schedulers:DatabaseScheduler

    worker:
        image: gpodder_app
        restart: always
        depends_on:
            - app
        environment:
            EMAIL_BACKEND: django.core.mail.backends.console.EmailBackend
            SECRET_KEY: ${SECRET_KEY}
            DATABASE_URL: postgres://mygpo:mygpo@db/mygpo
            LOGGING_CELERY_LEVEL: INFO
        volumes:
            - "./media:/usr/src/mygpo/media"
        entrypoint:
            - celery
            - -A
            - mygpo
            - -b
            - "redis://redis:6379//"
            - worker

networks:
    caddy:
        external:
            name: caddy_default
